version: '3.4'
services:
    db:
        image: mcr.microsoft.com/azure-sql-edge
        ports:
            - '1433:1433'
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: 'SqlExpress!'
    webapi:
        build:
            context: .
            dockerfile: WebAPI/Dockerfile
        depends_on:
            - db
        ports:
            - '5000:80'
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    wasm:
        build:
            context: .
            dockerfile: ClientBlazor/Dockerfile
        depends_on:
            - webapi
        ports:
            - 8888:80
